services:
  tne_local_hugo:
    image: floryn90/hugo:0.145.0-ext-ubuntu
    command: server --forceSyncStatic --cleanDestinationDir --disableFastRender
    volumes:
      - ".:."
    ports:
      - 1313:1313
