baseURL = "http://opensquare-local.nyupress.org"
[params]
	sassOutputFormat = "expanded"
	enableSourceMap = "true"
	pathtoreader = "https://opensquare-local.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
	connectedyouthurl = "https://localhost/connectedyouth"
