## Configuration file for local environment

baseURL = "http://localhost/opensquare"
[params]
	sassOutputFormat = "expanded"
  enableSourceMap = "true"
  pathtoreaderfiles = "https://opensquare.nyupress.org/open-square-reader/cloud-reader/epub_content/"
  pathtoreader = "https://opensquare.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
	connectedyouthurl = "https://localhost/connectedyouth"
