## production environment

baseURL = "https://opensquare.nyupress.org"

[services]
  [services.googleAnalytics]
    ID = 'UA-51495518-1'

[params]
	sassOutputFormat = "compressed"
	enableSourceMap = "false"
	pathtoreader = "https://opensquare.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
	connectedyouthurl = "https://connectedyouth.nyupress.org"
  googleanalyticsconnectedyouth = "UA-51495518-3"
  googleanalytics4 = "G-6ZBRSG08EY"
