## production environment

baseURL = "https://opensquare.nyupress.org"
googleAnalytics = "UA-51495518-1"
[params]
	sassOutputFormat = "compressed"
	enableSourceMap = "false"
	pathtoreader = "https://opensquare.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
	connectedyouthurl = "httpsx://connectedyouth.nyupress.org"
  googleanalyticsconnectedyouth = "UA-51495518-3"
