## production environment

baseURL = "https://opensquare.nyupress.org"

[services]
  [GoogleAnalytics]
    ID = 'G-6ZBRSG08EY'

[params]
  sassOutputFormat = "compressed"
  enableSourceMap = "false"
  pathtoreader = "https://opensquare.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
  pathtoreaderfiles = "https://opensquare.nyupress.org/open-square-reader/cloud-reader/epub_content/"
  connectedyouthurl = "https://connectedyouth.nyupress.org"
  matomoanalyticsid = "18"
