## production environment

baseURL = "https://opensquare.nyupress.org"

[params]
  apiurl = "https://sites.dlib.nyu.edu/viewer/api/v1/epubs/nyu-press"
  sassOutputFormat = "compressed"
  enableSourceMap = "false"
  pathtoreader = "https://opensquare.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
  pathtoreaderfiles = "https://opensquare.nyupress.org/open-square-reader/cloud-reader/epub_content/"
  connectedyouthurl = "https://connectedyouth.nyupress.org"
  matomoanalyticsid = "18"
  googleanalyticsid = "G-6ZBRSG08EY"

