baseURL = "https://opensquare-dev.nyupress.org"

disableKinds = ['sitemap']

[params]
	sassOutputFormat = "expanded"
	enableSourceMap = "true"
	connectedyouthurl = "https://connectedyouth-dev.nyupress.org"
