baseURL = "http://opensquare-dev.nyupress.org"
[params]
	sassOutputFormat = "expanded"
	enableSourceMap = "true"
	pathtoreader = "http://opensquare-dev.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
	connectedyouthurl = "http://connectedyouth-dev.nyupress.org"
    thumbhrefurl = "http://opensquare-dev.nyupress.org/open-square-reader"
