## Configuration file for development environment

baseURL = "https://opensquare-dev.nyupress.org"

[params]
	sassOutputFormat = "expanded"
	enableSourceMap = "true"
	connectedyouthurl = "https://connectedyouth-dev.nyupress.org"
