## Configuration file for stage environment

baseURL = "https://opensquare-stage.nyupress.org"

[params]
  pathtoreaderfiles = "https://opensquare-stage.nyupress.org/open-square-reader/cloud-reader/epub_content/"
  pathtoreader = "https://opensquare-stage.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
  connectedyouthurl = "https://connectedyouth-stage.nyupress.org"
  matomoanalyticsid = "18"
  googleanalyticsid = "G-6ZBRSG08EY"

