## config file for stage environment

baseURL = "https://opensquare-stage.nyupress.org"

disableKinds = ['sitemap']

[params]
	sassOutputFormat = "compressed"
	enableSourceMap = "false"
	pathtoreader = "https://opensquare-stage.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
	connectedyouthurl = "https://connectedyouth-stage.nyupress.org"
