## config file for stage environment

baseURL = "https://opensquare-stage.nyupress.org"

disableKinds = ['sitemap']

[services]
  [GoogleAnalytics]
    ID = 'G-6ZBRSG08EY'

[params]
	sassOutputFormat = "compressed"
	enableSourceMap = "false"
	connectedyouthurl = "https://connectedyouth-stage.nyupress.org"
  matomoanalyticsid = "18"

