## config file for stage environment

baseURL = "https://opensquare-stage.nyupress.org"

disableKinds = ['sitemap']

[params]
	sassOutputFormat = "compressed"
	enableSourceMap = "false"
	connectedyouthurl = "https://connectedyouth-stage.nyupress.org"
  matomoanalyticsid = "18"
  googleanalyticsid = "G-6ZBRSG08EY"

