## Configuration file for stage environment

baseURL = "https://opensquare-stage.nyupress.org"

[params]
  connectedyouthurl = "https://connectedyouth-stage.nyupress.org"
  matomoanalyticsid = "18"
  googleanalyticsid = "G-6ZBRSG08EY"

