## config file for stage environment

baseURL = "https://opensquare-stage.nyupress.org"

disableKinds = ['sitemap']

[services]
  [GoogleAnalytics]
    ID = 'G-6ZBRSG08EY'

[params]
	sassOutputFormat = "compressed"
	enableSourceMap = "false"
	pathtoreader = "https://opensquare-stage.nyupress.org/open-square-reader/cloud-reader/?epub=epub_content/"
	connectedyouthurl = "https://connectedyouth-stage.nyupress.org"
  googleanalyticsconnectedyouth = "UA-51495518-3"
  matomoanalyticsid = "18"

